entity_linking:
    url: http://0.0.0.0:8075/model
entity_detection:
    url: http://0.0.0.0:8103/respond

wikidata:
    transe: trans_model_weight/transe_wikidata5m.pkl
    dataset:
        train: dataset/wikidata5m_transductive_train.txt
        val: dataset/wikidata5m_transductive_valid.txt
        test: dataset/wikidata5m_transductive_test.txt
dataset:
    name: daily_dialog
    limit:
        train: 2000
        validation: 200
        test: 200
    postprocess:
        train: dataset/el_single_results_train.json
        val: dataset/el_single_results_validation.json
        test: dataset/el_single_results_test.json
